name: Convert PDF to JSON

on:
  push:
    paths:
      - 'input_data/*.pdf'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install PyMuPDF
        run: pip install pymupdf

      - name: Parse PDF to JSON
        run: python scripts/parse_pdf_to_json.py

      - name: Commit generated JSON
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add parsed_json/*.json
          git commit -m "Auto-generate JSON from uploaded PDF"
          git push
